### 認証成功パターン
POST http://localhost/login
Content-Type: application/json

{
  "userId": "TestUser",
  "password": "TestPass"
}

### 認証失敗パターン
POST http://localhost/login
Content-Type: application/json

{
  "userId": "hacker",
  "password": "wrong"
}
